- name: "SMB sharing"
  arensb.truenas.sharing_smb:
    name: "{{ item }}"
    path: "{{ pool }}/{{ item }}"
    purpose: DEFAULT_SHARE
    browsable: true
    enabled: true
  loop: "{{ smb_shares }}"
  tags:
  - smb_sharing
  - sharing

- name: "Enable SMB service"
  arensb.truenas.service:
    name: smbd
    state: started
    enabled: true
  tags: 
  - smb_sharing
  - sharing

- name: "Create home user"
  arensb.truenas.user:
    name: home
    group: "builtin_users"
    create_group: false
    home: "/nonexistent"
    password: "{{ home_pwd }}"
  tags: users
  # TODO: enable SMB auth afterwards

# Need to create specific plex group and user for plex to work
- name: "Create plex group"
  arensb.truenas.group:
    name: "{{ plex_group }}"
    gid: "{{ plex_id }}"
  tags: users

- name: "Create plex user"
  arensb.truenas.user:
    name: "{{ plex_user }}"
    uid: "{{ plex_id }}"
    create_group: false
    home: "/nonexistent"
    password: "{{ plex_pwd }}"
  # TODO: enable SMB auth afterwards
  tags: users

- name: "Set hostname"
  arensb.truenas.hostname:
    name: tamrieltower

- name: "Daily snapshots"
  arensb.truenas.pool_snapshot_task:
    match:
      dataset: default
      name_format: "snapshot-daily-"
    dataset: default
    lifetime_value: 30
    lifetime_unit: days
    name_format: "snapshot-daily-%Y-%m-%d_%H:%M"
    recursive: true
    exclude:
      - default/media
    minute: "0"
    hour: "5"
    day: "*"
    month: "*"
    weekday: "*"
  tags: snapshots
