- name: restart plex
  service:
    name: plexmediaserver
    state: restarted

- name: reload ssh
  become: true
  service:
    name: ssh
    state: reloaded

- name: reload ufw
  become: true
  ufw:
    state: reloaded