- name: ssh forbid login with passwords and root
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" }
  notify:
    - reload ssh

- name: ufw install
  apt: state=present name=ufw

- name: Set logging
  ufw:
    logging: 'on'

- name: ufw allow ssh
  ufw:
    rule: allow
    name: OpenSSH
  notify:
  - reload ufw

- name: UFW allow plex port and protocol
  ufw:
    rule: allow
    port: "32400"
    protocol: tcp
  notify:
  - reload ufw


- name: ufw rate limit ssh
  become: true
  ufw:
    rule: limit
    port: ssh
    proto: tcp
  notify:
  - reload ufw

- name: ufw deny incoming
  become: true
  ufw:
    direction: incoming
    proto: any
    policy: deny
  notify:
  - reload ufw

- name: ufw allow outgoing
  become: true
  ufw:
    direction: outgoing
    proto: any
    policy: allow
  notify:
  - reload ufw

- name: ufw enable service
  become: true
  ufw:
    state: enabled